backend:
  name: github
  repo: itsupport-web/testing

media_folder: /static/media
public_folder: /media

collections:
  - name: pages
    label: pages
    folder: /content/pages
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
  - name: posts
    label: posts
    folder: /content/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
